-- Use SQL insert statements to add any
-- starting/dummy data to your database tables

-- EXAMPLE:

--  insert into "todos"
--    ("task", "isCompleted")
--    values
--      ('Learn to code', false),
--      ('Build projects', false),
--      ('Get a job', false);

INSERT INTO "products" ("productId", "name", "category", "price", "description", "imageUrl")
VALUES
  (1, 'Balenciaga Track', 'shoe', 500.00, 'Balenciaga trainer sneaker with caged upper.', '/products/balenciaga-track.jpg'),
  (2, 'Balenciaga TripleS', 'shoe', 600.00, 'Balenciaga double foam and mesh sneaker.', '/products/balenciaga-triples.jpg'),
  (3, 'BAPE Bearbrick', 'accessory', 800.00, 'Medicom Toy partnered with BAPE on a limited edition Daruma Bearbrick to celebrate the Japanese New Year.', '/products/bape-bearbrick.jpg'),
  (4, 'BAPE Camo Black Shirt', 'top', 100.00, 'BAPE Cotton jersey T-shirt.', '/products/bape-camo-shirt-black.jpg'),
  (5, 'BAPE Camo White Shirt', 'top', 100.00, 'BAPE Cotton jersey T-shirt.', '/products/bape-camo-shirt-white.jpg'),
  (6, 'BAPE Camo Black Shorts', 'bottom', 100.00, 'Shark-print track shorts.', '/products/bape-camo-shorts-black.jpg'),
  (7, 'BAPE Milo Rug', 'accessory', 500.00, 'Round tufted rug featuring signature graphic in black, brown, orange, and yellow. Non-slip rubber backing. 100% polyester.', '/products/bape-milo-rug.jpg'),
  (8, 'Fear of God White Hoodie', 'top', 200.00, 'Printed with Essentials across the front. From SS21, the style features a second logo printed on the sleeve and a rubberized logo on top of the hood', '/products/fear-of-god-hoodie-white.jpg'),
  (9, 'Fear of God x Nike Black Shorts', 'bottom', 300.00, 'Paying homage to basketball staples of the past with a contemporary update, this loose-fitting pair are designed to look good both on and off the hardwood; boasting a shiny black outer, two pockets to the front and an elasticated drawstring waist for easy wear', '/products/fear-of-god-nike-shorts-black.jpg'),
  (10, 'Fear of God White Shorts', 'bottom', 200.00, 'The Fear of God FOG Essentials Drawstring Shorts White are knee-length shorts made of a white cotton blend material combination with drawstring fastening at the waist, and two side slit pockets. This garment by Fear of God FOG Essentials has two side slit pockets, both with a black zipper.', '/products/fear-of-god-shorts-white.jpg'),
  (11, 'Jordan Black Cement 3', 'shoe', 500.00, 'The Air Jordan 3 ''Black Cement'' is a black and grey version of Michael Jordan''s third signature shoe. It originally released in 1988, followed by 1994, 2001, 2008, and 2011 featuring a mix of leather, elephant print, and visible Air.', '/products/jordan-black-cement-3.jpg'),
  (12, 'Jordan Black/Red 1', 'shoe', 500.00, 'The Air Jordan 1 High Bred Patent features black and red patent leather upper with signature weaved Nike Air tongue labels. From there, a classic Wings logo on the collar and a white with red Air sole complete the retro design.', '/products/jordan-bred-1.jpg'),
  (13, 'Jordan Black/Red 11', 'shoe', 500.00, 'The Jordan 11 features a black upper with shiny patent leather overlays and red detailing. A red translucent outsole, white midsole, and "23" insignia on the heel completes the design.', '/products/jordan-bred-11.jpg'),
  (14, 'Jordan Mocha 1', 'shoe', 750.00, 'The upper of the Jordan 1 High Dark Mocha features a Sail leather base with black leather surrounding the toe box and Mocha suede on the heel and ankle. A black leather Swoosh, Jordan Wings logo on the ankle, and Nike Air branding on the tongue pays homage to branding that can be found on the original 1985 Jordan 1. A Sail midsole and black outsole complete this Black Toe design.', '/products/jordan-mocha-1.jpg'),
  (15, 'Jordan OFF WHITE x UNC 1', 'shoe', 750.00, 'Time for some Tobacco Road vibes with these Jordan 1 Retro Off-Whites. Also known as the "UNC" editions, these Jordan 1s are the third colorway designed by Virgil Abloh and made in collaboration with his Off-White label. The sneakers come in a white, dark powder blue and cone colorway, with a white and blue deconstructed leather upper and Off-White detailing throughout. If you’re a fan of Virgil Abloh’s work and want to rep Off-White, this pair is another must-have.', '/products/jordan-offwhite-1.jpg'),
  (16, 'Kith Blue Hoodie', 'top', 750.00, 'A ribbed hem and sleeve cuffs, a drawcord-adjustable hood, and is complete with Kith logo embroidery on the front.', '/products/kith-hoodie-blue.jpg'),
  (17, 'Kith Grey Hoodie', 'top', 750.00, 'A ribbed hem and sleeve cuffs, a drawcord-adjustable hood, and is complete with Kith logo embroidery on the front.', '/products/kith-hoodie-grey.jpg'),
  (18, 'Off White Industrial Belt', 'accessory', 450.00, 'The Off-White Industrial Belt is potentially the most well-recognized and popular item the brand has ever made. The yellow and black version is the most classic iteration of the belt and features Off-White branding as well as red stitching down the middle. This belt has been seen on celebrities both inside and outside of Virgil Abloh''s direct circle, from Lil Uzi Vert to Tan France. This particular Off-White Industrial Belt retailed for $225 USD but has primarily resold on StockX for below retail.', '/products/off-white-industrial-belt.jpg'),
  (19, 'Palace Green Hoodie', 'top', 750.00, 'This Palace Hoodie features a Palace logo print on the front and back. A high-quality green fabric completes the streetwear look.', '/products/palace-hoodie-green.jpg'),
  (20, 'Stussy x Nike White Shirt', 'top', 250.00, 'The Nike x Stussy The Wide World Tribe T Shirt White is a collaboration between two iconic brands that showcases a unique design inspired by global travel and exploration. The shirt features a white base color with a bold graphic print on the front that depicts a globe with various landmarks and symbols.', '/products/stussynike-shirt-white.jpg'),
  (21, 'Supreme Bottle', 'accessory', 100.00, 'For this SS18 accessory, Supreme tapped Swiss manufacturing company Sigg to produce a 0.6L aluminum water bottle. The bottle, which holds about 20 fluid ounces, originally released on March 8th, 2018, and sold immediately at a retail price of $36. Supreme followed up with a restock in April, due to the popularity of the bottle. Again, they flew off the digital shelf in no time. The clean and understated design is perfect for any occasion, and is just what you need to keep yourself hydrated all summer (and all year) long.', '/products/supreme-bottle.jpg'),
  (22, 'Supreme Fanny Pack', 'accessory', 250.00, 'This Supreme Waist Bag released on February 15th, 2018, the brand''s SS18 opening week. This bag has since gone on to become one of the most traded Supreme bags on StockX. Featuring dual pockets and Supreme branding on both the front and the strap, it should come as little surprise that this bag has been resold by the thousands since its release. The black Supreme Waist Bag from SS18 was released at a retail price of $88 and trades now at an average sale price of three times that.', '/products/supreme-fanny-pack.jpg'),
  (23, 'Supreme Black Mesh Short', 'bottom', 250.00, 'Supreme Small Box Baggy Mesh Short Black Men''s from SS23.', '/products/supreme-mesh-short-black.jpg'),
  (24, 'Supreme x North Face White Jacket', 'top', 1050.00, 'Looking for a The North Face x Supreme collab that feels a little more like a traditional TNF fleece? Look no further. Featuring materials from the likes of Cordura and GORE-TEX, this collaborative fleece was made for The North Face purists and the Supreme fans alike. This unique red and white jacket takes the traditional TNF fleece and adds both color blocking and dual chest pockets and includes the infamous The North Face and Supreme logos on the right arm. The jacket was released on November 29th, 2018 and retailed at a $328 USD. Place a bid today to stay cozy this winter.', '/products/supremenorthface-jacket-white.jpg'),
  (25, 'Supreme Red Camo Backpack', 'accessory', 500.00, 'The Supreme Backpack SS21 Red Camo is a stylish and functional accessory that is perfect for everyday use. Made from high-quality materials, this backpack is durable and built to last. The red camo colorway adds a bold and eye-catching touch to any outfit. This backpack features a spacious main compartment with a zippered closure, as well as a front zippered pocket for additional storage. The adjustable shoulder straps ensure a comfortable fit, while the top handle allows for easy carrying.', '/products/supreme-red-backpack.jpg'),
  (26, 'Yeezy Foam Rnnrs', 'shoe', 500.00, 'Following previous monochromatic Foam RNNRs, the adidas Yeezy Foam RNNR MX Cream Clay is the first Foam RNNR to feature a multicolor palette. Cream, clay, and grey colors are all prominent on the upper in a streaked camo pattern, making the design a true statement piece.', '/products/yeezy-foam-rnnrs.jpg'),
  (27, 'Yeezy Boost 350 Turledoves', 'shoe', 500.00, 'Released in 2015, the adidas Yeezy Boost 350 Turtle Dove is the first colorway to kick off Yeezy''s expansive 350 line. Composed of a grey and brown patterned Primeknit, the design was one of the most comfort focus Yeezy designs at the time and still is to this day. At the base, a grooved Boost outsole delivers adidas'' renowned cushioning.', '/products/yeezy-turtledoves.jpg'),
  (28, 'Yeezy Boost 700 Waverunners', 'shoe', 500.00, 'The Yeezy 700 Boost Wave Runner is the shoe that led Yeezy pivot from a sleek, minimal aesthetic to a chunky, 90s inspired one. This was the gateway sneaker between knit runners like the 350 and the grungy skate look of the 550. The Yeezy 700 Wave Runner features a grey mesh and leather upper with black suede overlays and teal mesh underlays. At the base, a thick Boost sole and contrasting hits of orange complete the design.', '/products/yeezy-waverunners.jpg')
